language: rust
rust:
  - stable
  - beta
# Cache settings based on https://levans.fr/rust_travis_cache.html
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry

before_install:
  - rustup component add rustfmt
  - cargo fmt -- --check
